# Project information
site_name: Hello 算法
site_url: https://www.hello-algo.com/
site_author: Krahets
site_description: 一本动画图解、能运行、可提问的数据结构与算法入门书
docs_dir: build
# Repository
repo_name: krahets/hello-algo
repo_url: https://github.com/krahets/hello-algo
edit_uri: https://github.com/krahets/hello-algo/tree/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Krahets

# Configuration
theme:
  name: material
  custom_dir: build/overrides
  language: zh
  features:
    # - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      # accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      # primary: grey
      # accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Noto Sans SC
    code: Fira Code
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/krahets
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/krahets
    - icon: fontawesome/solid/code 
      link: https://leetcode.cn/u/jyd/
  generator: false

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - 0. &nbsp; &nbsp; 写在前面:
    - 0.1. &nbsp; 关于本书: chapter_preface/about_the_book.md
    - 0.2. &nbsp; 如何使用本书: chapter_preface/suggestions.md
  - 1. &nbsp; &nbsp; 引言:
    - 1.1. &nbsp; 算法无处不在: chapter_introduction/algorithms_are_everywhere.md
    - 1.2. &nbsp; 算法是什么: chapter_introduction/what_is_dsa.md
    - 1.3. &nbsp; 小结: chapter_introduction/summary.md
  - 2. &nbsp; &nbsp; 复杂度分析:
    - 2.1. &nbsp; 算法效率评估: chapter_computational_complexity/performance_evaluation.md
    - 2.2. &nbsp; 时间复杂度: chapter_computational_complexity/time_complexity.md
    - 2.3. &nbsp; 空间复杂度: chapter_computational_complexity/space_complexity.md
    - 2.4. &nbsp; 权衡时间与空间: chapter_computational_complexity/space_time_tradeoff.md
    - 2.5. &nbsp; 小结: chapter_computational_complexity/summary.md
  - 3. &nbsp; &nbsp; 数据结构简介:
    - 3.1. &nbsp; 数据与内存: chapter_data_structure/data_and_memory.md
    - 3.2. &nbsp; 数据结构分类: chapter_data_structure/classification_of_data_structure.md
    - 3.3. &nbsp; 小结: chapter_data_structure/summary.md
  - 4. &nbsp; &nbsp; 数组与链表:
    - 4.1. &nbsp; 数组: chapter_array_and_linkedlist/array.md
    - 4.2. &nbsp; 链表: chapter_array_and_linkedlist/linked_list.md
    - 4.3. &nbsp; 列表: chapter_array_and_linkedlist/list.md
    - 4.4. &nbsp; 小结: chapter_array_and_linkedlist/summary.md
  - 5. &nbsp; &nbsp; 栈与队列:
    - 5.1. &nbsp; 栈: chapter_stack_and_queue/stack.md
    - 5.2. &nbsp; 队列: chapter_stack_and_queue/queue.md
    - 5.3. &nbsp; 双向队列: chapter_stack_and_queue/deque.md
    - 5.4. &nbsp; 小结: chapter_stack_and_queue/summary.md
  - 6. &nbsp; &nbsp; 散列表:
    - 6.1. &nbsp; 哈希表: chapter_hashing/hash_map.md
    - 6.2. &nbsp; 哈希冲突处理: chapter_hashing/hash_collision.md
    - 6.3. &nbsp; 小结: chapter_hashing/summary.md
  - 7. &nbsp; &nbsp; 树:
    - 7.1. &nbsp; 二叉树: chapter_tree/binary_tree.md
    - 7.2. &nbsp; 二叉树遍历: chapter_tree/binary_tree_traversal.md
    - 7.3. &nbsp; 二叉搜索树: chapter_tree/binary_search_tree.md
    - 7.4. &nbsp; AVL 树 *: chapter_tree/avl_tree.md
    - 7.5. &nbsp; 小结: chapter_tree/summary.md
  - 8. &nbsp; &nbsp; 堆:
    - 8.1. &nbsp; 堆: chapter_heap/heap.md
    - 8.2. &nbsp; 建堆操作 *: chapter_heap/build_heap.md
    - 8.3. &nbsp; 小结: chapter_heap/summary.md
  - 9. &nbsp; &nbsp; 图:
    - 9.1. &nbsp; 图: chapter_graph/graph.md
    - 9.2. &nbsp; 图基础操作: chapter_graph/graph_operations.md
    - 9.3. &nbsp; 图的遍历: chapter_graph/graph_traversal.md
    - 9.4. &nbsp; 小结: chapter_graph/summary.md
  - 10. &nbsp; &nbsp; 查找算法:
    - 10.1. &nbsp; 线性查找: chapter_searching/linear_search.md
    - 10.2. &nbsp; 二分查找: chapter_searching/binary_search.md
    - 10.3. &nbsp; 哈希查找: chapter_searching/hashing_search.md
    - 10.4. &nbsp; 小结: chapter_searching/summary.md
  - 11. &nbsp; &nbsp; 排序算法:
    - 11.1. &nbsp; 排序简介: chapter_sorting/intro_to_sort.md
    - 11.2. &nbsp; 冒泡排序: chapter_sorting/bubble_sort.md
    - 11.3. &nbsp; 插入排序: chapter_sorting/insertion_sort.md
    - 11.4. &nbsp; 快速排序: chapter_sorting/quick_sort.md
    - 11.5. &nbsp; 归并排序: chapter_sorting/merge_sort.md
    - 11.6. &nbsp; 小结: chapter_sorting/summary.md
  - 12. &nbsp; &nbsp; 附录:
    - 12.1. &nbsp; 编程环境安装: chapter_appendix/installation.md
    - 12.2. &nbsp; 一起参与创作: chapter_appendix/contribution.md
  - 参考文献:
    - chapter_reference/index.md
